name: Destroy Playground

on:
  pull_request:
    types:
      - closed

env:
  AWS_DEFAULT_REGION: 'eu-west-1'
  AWS_REGION: 'eu-west-1'
  ENVIRONMENT: 'playground'
  AWS_ACCOUNT_NUMBER: '905353286448'

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Extract branch name
        id: set-extract-branch
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_HEAD_REF#refs/heads/})"

      - name: Get Playground Identity
        id: set-playground-id
        run: |
          export BRANCH_HASH=`echo ${GITHUB_HEAD_REF#refs/heads/} | md5sum | cut -c1-5`
          echo "::set-output name=playground_id::${BRANCH_HASH}"
    outputs:
      playground-id: pg${{ steps.set-playground-id.outputs.playground_id }}
      branch-name: ${{ steps.set-extract-branch.outputs.branch }}

  destroy-playground-project:
    name: 'Destroy Playground Project'
    runs-on: ubuntu-latest
    needs:
      - setup
    steps:
      - name: Checking Source
        uses: 'actions/checkout@v2'

      - name: Restore node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: v1-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Configure node and npm
        uses: actions/setup-node@v2-beta
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
          scope: 'Hammamsgit'

      - name: npm ci
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GHP_TOKEN }}

      - name: Configure AWS credentials (Sandbox)
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_NUMBER }}:role/infrastructure/service-deployment-partner-marketplace
          role-session-name: service-deployment-partner-marketplace
          aws-region: eu-west-1

      - name: destroy environment
        run: |
          npx ts-node bin/manage-playground-env.ts --action destroy --id ${{ needs.setup.outputs.playground-id }} --branch-name ${{ needs.setup.outputs.branch-name }}

      - name: comment on pr
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: 🔴 Playground environment `${{ needs.setup.outputs.pr-id }}` DESTROYED
          check_for_duplicate_msg: false
